site_name: C1 Wiki

repo_url: https://github.com/WillHouMoe/c1-wiki
repo_name: WillHouMoe/c1-wiki

nav:
  - 首页: index.md
  - 梗指南:
    - meme/index.md
    - 鼓掌: meme/applause.md
    - 难度两颗星: meme/two-stars.md
    - 报警: meme/call-the-police.md
    - 刘老师说的对吧: meme/am-i-right.md
    - 一到十八: meme/one-to-eighteen.md
    - 交上来: meme/hand-it-over.md
    - 下班: meme/time-to-go.md
    - 抱头痛哭: meme/burst-out-crying.md
    - 刘___的________: meme/can-not-translate.md
    - 夏牧言的_______: meme/gem-of-eldone.md
    - 孩子们~: meme/kids.md
    - 又进化了: meme/evolution.md
    - 打两个: meme/lets-go.md
    - 这是魔方吗: meme/is-this-a-cube.md
    - 夏收言、氨牧言、氨收言: meme/an-shou-yan.md
    - 头抬起来！: meme/heads-up.md
    - 两圆一垂: meme/a-math-problem.md
    - 敖小凤不等式: meme/ao-inequality.md
    - 其实不蓝: meme/in-fact-not-blue.md
    - 万晨小熙熙: meme/little-wcx.md
    - 海猴子: meme/sea-monkey.md
    - 一个拉 shi 一个递纸: meme/where-do-they-go.md
    - f 打头的单词: meme/the-f-word.md
    - 奠基法: meme/dian-ji-fa.md
    - 32 号，出列！: meme/eldone-out.md
    - 刘总の三个预言: meme/three-predictions.md
    - EG DE 等: meme/eg-de-abbreviation.md
  - 参与编辑: 
    - direction/index.md
    - 编写规则: direction/rules.md
    - 关于 Markdown: direction/markdown.md
    - C1 Wiki 解析规范: direction/render.md
    - 负责人和撰稿人: direction/leader.md
  - 博客:
    - blog/index.md

theme: 
  name: material
  palette:
    primary: white
  language: zh
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - navigation.tabs
    - navigation.indexes
  icon:
    repo: fontawesome/brands/git-alt

plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - glightbox

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
