authors:
  WillHou:
    name: WillHou
    description: Creator
    avatar: https://cdn.luogu.com.cn/upload/image_hosting/3afg4gyl.png
    url: https://github.com/WillHouMoe
  Owencjs:
    name: Owencjs
    description: Leader & Writer
    avatar: https://avatars.githubusercontent.com/u/87080007
    url: https://github.com/Owencjs